apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      labels:
        app: register-app
    spec:
      containers:
        - name: register-app

          image: shekharkops/register-app-pipeline:1.0.0-13
          resources:
            limits:
              memory: "256Mi"
              cpu: "502m"
          ports:
            - containerPort: 8080
